### ISSUE TITLE
false positive

### ISSUE THREAD

**Issue by hyder365** [hectorm/hmirror#10]
Hi.

https://raw.githubusercontent.com/hectorm/hmirror/master/data/digitalside-threat-intel/list.txt

This file is blocking transfer.sh, which is a legitimate command line file-sharing website. Could it be removed please?

**Comment by hectorm** [comment]
I've reported this issue to upstream (davidonzo/Threat-Intel#19) and I've released [a new hBlock version](https://github.com/hectorm/hblock/releases/tag/v3.2.3) removing this list.

I don't have much more to do on my side so I'm going to close this issue.

Thanks for the notice!
