### ISSUE TITLE
[false positive] bitbucket.org blocked again

### ISSUE THREAD

**Issue by Polpetta** [hectorm/hmirror#12]
Hi,
bitbucket.org, a website that hosts source code is blocked again (see #11).
I searched in this repository and I found it here: https://github.com/hectorm/hmirror/blob/407b7fd2814e2b49db840eb815384efe9513e7f2/data/adguard-cname-trackers/list.txt#L2542

Can this be whitelisted please?
Thank you! :blush:

**Comment by hectorm** [comment]
Thanks for the warning!

It looks like it was added in AdguardTeam/cname-trackers@c8450b1b2a078507e85586cc8ccfd063fe344f69 and removed in AdguardTeam/cname-trackers@ada2d16b40226130dc9fed9820998d49aa9c859c.

I have run a manual update of the lists and the problem is now solved.
