### ISSUE TITLE
pgl.yoyo.org list is blocking Twitter t.co

### ISSUE THREAD

**Issue by jkumeboshi** [hectorm/hmirror#16]
following list contains t.co domain:

https://raw.githubusercontent.com/hectorm/hmirror/master/data/pgl.yoyo.org/list.txt 

this will block any Twitter short link.
Looks like its the only list containing it.

I'm going to white list it in my DNS resolver, but I think it should be removed

**Comment by hectorm** [comment]
I have temporarily removed the t.co domain from the pgl.yoyo.org source and paused its update until I make a decision.
