### ISSUE TITLE
Guides/Docs to use on my own server?

### ISSUE THREAD

**Issue by vdbhb59** [hectorm/hmirror#19]
Hi Mate,

As per the subject line, I wish to implement this mirrors option on my own server. Any guide or documentation to do it, would be really helpful for me.. :)

**Comment by hectorm** [comment]
I don't quite understand what you're trying to do.

This repository is just a mirror of third party sources, updated with a shell script and automated with a GitHub workflow. You can either fork this project and change the sources to whatever you want, or run this update process outside of GitHub and serve the files from your own web server.
