### ISSUE TITLE
New Logo/Icon proposal

### ISSUE THREAD

**Issue by mansya** [hectorm/hmirror#2]
Good day Sir I am a graphic designer and i am interested in designing a logo for your good project. I will be doing it as a gift for free. I just need your permission first before i begin my design. Hoping for your positive feedback. Thanks

**Comment by hectorm** [comment]
I consider that this project is too simple to need a logo, but there is another related project in which it would be great to have one, [hBlock Resolver](https://github.com/hectorm/hblock-resolver).

hBlock Resolver is a Docker image of [Knot DNS Resolver](https://www.knot-resolver.cz) configured to automatically block ads, tracking and malware domains with [hBlock](https://github.com/hectorm/hblock). hBlock already has a logo (see issue https://github.com/hectorm/hblock/issues/18), so the hBlock Resolver logo should be similar to maintain consistency. Feel free to open a new issue on the other project to discuss about the logo.
