### ISSUE TITLE
Better Handling of uBlock Syntax

### ISSUE THREAD

**Issue by sr093906** [hectorm/hmirror#20]
Example: https://github.com/uBlockOrigin/uAssets/blob/master/filters/badware.txt

It contains entries ending with ^$all or ^$doc but none of these entries are included in the converted list

https://github.com/hectorm/hmirror/blob/master/data/ublock-badware/list.txt

Ref: https://github.com/gorhill/uBlock/wiki/Strict-blocking

**Comment by hectorm** [comment]
Thanks for letting me know! I have just added support for it.
