### ISSUE TITLE
uBlock filters have been split into yearly sub-lists

### ISSUE THREAD

**Issue by gothic-bum** [hectorm/hmirror#21]
Hello Hector,

Since 2020, new uBlock filters are added to yearly sub-lists, which are not included in your [sources.json](https://github.com/hectorm/hmirror/blob/master/sources.json) file.

In addition to the original list (https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/filters.txt), here are the additional lists:  
  
https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/filters-2020.txt
https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/filters-2021.txt
https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/filters-2022.txt
https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/filters-2023.txt
  
And new lists will be created in 2024, 2025, etc.
   
So you may want to add these lists to ensure that you are getting all of the latest updates.
  
Best regards, and thanks for all of your efforts!

**Comment by hectorm** [comment]
Hi @gothic-bum, thanks for the heads-up!

I will try to find time this week to update the lists and release a new version of hBlock.

**Comment by hectorm** [comment]
Do you have more context on this? I see in the repository that past annual lists are still being updated and I don't quite understand their workflow.

**Comment by gothic-bum** [comment]
Entries that already existed in a previous file are updated (deleted, modified, etc) in that file. New entries are added to the yearly files. 

See commit from gorhill (the developer of uBO):
https://github.com/uBlockOrigin/uAssets/commit/bec59a796d5305f21b97074b35416e6260993d78

Specifically note:  

> ! As of 2020-04-09, new filters will be added to year-based sublists
