### ISSUE TITLE
archive.org being blocked

### ISSUE THREAD

**Issue by hyder365** [hectorm/hmirror#24]
https://raw.githubusercontent.com/hectorm/hmirror/master/data/digitalside-threat-intel/list.txt

contains "web.archive.org"

Whichever upstream source gave this should probably be reconsidered.

**Comment by hectorm** [comment]
It seems to have already been removed in https://github.com/davidonzo/Threat-Intel/commit/e28d08a0920a290e06ee658fd99a54c6a55b596b, I will reconsider including this source by default if more similar cases occur. Thanks!
