### ISSUE TITLE
false positive: transfer.adttemp.com.br

### ISSUE THREAD

**Issue by hyder365** [hectorm/hmirror#25]
The domain "transfer.adttemp.com.br" is a public instance of the transfer.sh software, used for temporary file hosting (similar to catbox.moe). It's currently on the blacklist. There's nothing inherently bad about it.

It's currently in this file of yours: https://raw.githubusercontent.com/hectorm/hmirror/master/data/urlhaus/list.txt

**Comment by hectorm** [comment]
This repository is just a mirror, you should report this upstream.
