### ISSUE TITLE
[request] add more sources

### ISSUE THREAD

**Issue by smed79** [hectorm/hmirror#3]
Hi,

could you please include the below Adblock Plus regional lists 

**Liste FR** ~ https://easylist-downloads.adblockplus.org/liste_fr.txt
**Liste AR** ~ https://easylist-downloads.adblockplus.org/Liste_AR.txt
**RU AdList** ~ https://easylist-downloads.adblockplus.org/advblock.txt
**EasyList Germany** ~ https://easylist-downloads.adblockplus.org/easylistgermany.txt
**EasyList China** ~ https://easylist-downloads.adblockplus.org/easylistchina.txt

thank you.

**Comment by hectorm** [comment]
Done.

**Comment by smed79** [comment]
Awesome, thank you.
