### ISSUE TITLE
Concatenated

### ISSUE THREAD

**Issue by jult** [hectorm/hmirror#4]
Is there a particular reason you don't just host 1 large blocklist where you delete all duplicates?
You know, like
```
wget -qO - https://some list urls.list >> /tmp/black
wget -qO - --limit-rate=1500k https://some other list2.txt >> /tmp/black
cat /somelocallist/black >> /tmp/black

sed '/^#/ d' < /tmp/black > /tmp/blist
dos2unix -q -n /tmp/blist /tmp/bl
sort /tmp/bl | uniq -u > /tmp/finalbl

``` 
It's really weird that nobody seems to be doing that. Who in their right mind, as an end user, is going to sift through all separate lists? Ideally everybody wants 1 hosted list on github, where people globally can add or remove entries in with valid arguments, and then have the same for whitelisting.

**Comment by hectorm** [comment]
This repository is simply a mirror of multiple blocklists, the concatenated list you ask for is what I literally offer in my other project, [hBlock](https://github.com/hectorm/hblock).

**Comment by jult** [comment]
Except you don't host such list, you host scripts that create the list. But thanks anyway.
I'm just surprised people don't seem to centralize their work. When push comes to shove that always works best for blacklists, just look at google's spam-flagging.
