### ISSUE TITLE
Blocking sentry.io

### ISSUE THREAD

**Issue by adamwojt** [hectorm/hmirror#8]
Took me a while to debug this one, two of lists are blocking https://sentry.io
https://forum.sentry.io/t/cannot-access-sentry-io-dashboard-website/13060
Is there way to filter these out?

**Comment by hectorm** [comment]
Hi, thank you for your time reporting this. Unfortunately this project is simply a mirror of other lists that I use mainly for the [hBlock](https://github.com/hectorm/hblock) project and I've no control over the domains included in them.

If you think it's a false positive you should contact the original list author.

In the meantime if you are an hBlock user you can add the domain to the allowlist.

**Comment by adamwojt** [comment]
Thanks @hectorm , I really appreciate your time and work done on hBlock project.

With existence of `allowlist` this can be closed, mainly I wanted to leave it out there so that maybe someone who faces same issue can find it. 

Took me a while to even realize and learn that I have `hblock` as it was installed by default with my `arcolinux` build. Or maybe I added it at some point during installation wizard and then forgot :)
