### ISSUE TITLE
cant customize cookie setting with googles new cookie dialog

### ISSUE THREAD

**Issue by LeSnake04** [hectorm/hmirror#9]
Google updated their cookie settings. I can accept all, but when trying to customize, they redirect to settings page, which redirect to https://googleads.g.doubleclick.net/ads/preferences/cu/optout?continue={token}, which is blocked by hblock

**Comment by hectorm** [comment]
Thanks for the notice, but the `googleads.g.doubleclick.net` domain is also used for ads and since hosts file or DNS blocking can only block the whole domain it should be kept on the list.

If you want to access the domain you can add it to the allowlist.
